name: Parser Error
description: Use this if an error occurred while generating calendars.
body:
  - type: textarea
    attributes:
      label: MyOntarioTech schedule data
      description: Please paste exactly what you pasted into the app without any changes, so that I can use the data to reproduce the issue.
      render: text
    validations:
      required: true
  - type: textarea
    attributes:
      label: Console output
      render: text
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other information
