name: CI

on:
  push:
    branches: '**'
    tags: 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin-suffix:

          - name: linux-arm64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bin-suffix:

          - name: windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin-suffix: .exe

          - name: macos-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            bin-suffix:

          - name: macos-arm64
            os: macos-latest
            target: aarch64-apple-darwin
            bin-suffix:

    runs-on: ${{ matrix.os }}
    env:
      BIN: mycampus-calendar-rs${{ matrix.bin-suffix }}
      OUT: mycampus-calendar-rs-${{ matrix.name }}${{ matrix.bin-suffix }}

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Build
        uses: houseabsolute/actions-rust-cross@v0.0.14
        with:
          target: ${{ matrix.target }}
          args: --locked --release

      - name: Rename executable
        run: cp target/${{ matrix.target }}/release/${{ env.BIN }} ${{ env.OUT }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.name }}
          path: ${{ env.OUT }}
          if-no-files-found: error
  
  release:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: build
          pattern: build-*
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
          generate_release_notes: true
